config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items
  end

  root 'todo_lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  validates :content, presence: true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items, dependent: :destroy

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)

    if !@todo_item.save
      flash[:warning] = "Todo Item couldn't be saved. Try again."
    end

    redirect_to @todo_list
  end

  def destroy
    @todo_item.destroy
    redirect_to @todo_list
  end

  def edit
  end

  def update
    if @todo_item.update_attributes(todo_item_params)
      flash[:success] = "Todo Item successfully updated."
    else
      render 'edit'
    end

    redirect_to @todo_list
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  def index
    @todo_lists = TodoList.all
  end

  def new
    @todo_list = TodoList.new
  end

  def create
    @todo_list = TodoList.create(todo_list_params)

    if @todo_list.save
      flash[:success] = "The Todo List has been created succeefully."
    else
      flash[:warning] = "The Todo List cannot be created. Check the inputs."
    end
    redirect_to root_path
  end

  def show
  end

  def edit
  end

  def update
    @todo_list.update(todo_list_params)

    if @todo_list.save
      flash[:success] = "The Todo List has been updated succeefully."
    else
      flash[:warning] = "The Todo List cannot be updated. Check the inputs."
      render :new
    end
    redirect_to root_path
  end

  def destroy
    @todo_list.destroy
    redirect_to root_path
  end

  private

  def todo_list_params
    params.require(:todo_list).permit(:title, :description)
  end

  def set_todo_list
    @todo_list = TodoList.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
  </head>

  <meta name="viewport" content="height=device-height, width=device-width, initial-scale=1.0">

  <body>
    <div class="content" id="todo-main">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>"><%= msg %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/todo_items/_todo_item.html.erb
<% if TodoItem.exists?(todo_item.id) %>
<li class="list-group-item" id="todo-lists">

  <div class="row" id="todo-item-list">
    <div class="todo-item-on-todo-list-detail">
      <%= todo_item.content %>
    </div>
    <div class="todo-item-edit-on-todo-list-deail">
    <%= link_to edit_todo_list_todo_item_path(@todo_list, todo_item.id) do %>
      <button id="edit-btn"></button>
    <% end %>
    </div>
    <div class="todo-item-delete-on-todo-list-deail">
    <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
      <button id="delete-btn"></button>
    <% end %>
    </div>
  </div>
</li>
<% end %>

app/views/todo_items/edit.html.erb
<ul class="list-group">
<%= form_for ([@todo_list, @todo_item]) do |f| %>
  <li class="list-group-item" id="todo-list">
    <div class="page-title">
      Edit Todo Item
    </div>
    <div class="edit-todo-item-list-title">
        Todo Item in <%= @todo_list.title %>
    </div>
    <div class="edit-todo-item-content">
      <div class="edit-todo-item-title">
      Content:
      </div>
      <div>
      <%= f.text_field :content, id: "edit-todo-item-content" %>
      </div>
    </div>
  </li>
  <li class="list-group-item" id="create-todo-list">
    <%= f.submit "Update", id: "bottom-btn" %>
  </li>
<% end %>
</ul>
<div id="edit-todo-bottom-nav">
  <%= link_to 'Back', todo_list_path(@todo_list) %>
  |
  <%= link_to 'Home', root_path %>
</div>

app/views/todo_lists/_todo_list.html.erb
<% if !current_page?(root_path) %>
<br>
<%= link_to 'Back to Todo Lists', root_path %>
<% end %>

app/views/todo_lists/edit.html.erb
<ul class="list-group">
<%= form_for @todo_list do |f| %>
  <li class="list-group-item" id="todo-list">
    <div class="page-title">
      Edit Todo List
    </div>
    <div class="new-todo-list-title">
        Title
      <div>
        <%= f.text_field :title, id: "new-todo-list-text" %>
      </div>
    </div>
    <div class="new-todo-list-description">
      <div>
      Description
      </div>
      <div>
      <%= f.text_area :description %>
      </div>
    </div>
  </li>
  <li class="list-group-item" id="create-todo-list">
    <%= f.submit "Update", id: "bottom-btn" %>
  </li>
<% end %>
</ul>
<div id="edit-todo-bottom-nav">
  <%= link_to 'Back', todo_list_path(@todo_list) %>
  |
  <%= link_to 'Home', root_path %>
</div>

app/views/todo_lists/index.html.erb
<ul class="list-group">
<% @todo_lists.each do |todo_list| %>
  <li class="list-group-item" id="todo-lists">
    <div class="todo-list-title">
      <%= link_to todo_list.title, todo_list_path(todo_list.id) %> 
    </div>
    <div class="todo-list-description">
      <%= todo_list.description %>
    </div>
  </li>
<% end %>
  <li class="list-group-item" id="create-todo-list">
    <%= link_to 'New Todo List', new_todo_list_path %>
  </li>
</ul>

app/views/todo_lists/new.html.erb
<ul class="list-group">
<%= form_for @todo_list do |f| %>
  <li class="list-group-item" id="todo-list">
    <div class="page-title">
      New Todo List
    </div>
    <div class="new-todo-list-title">
        Title
      <div>
        <%= f.text_field :title, id: "new-todo-list-text" %>
      </div>
    </div>
    <div class="new-todo-list-description">
      <div>
      Description
      </div>
      <div>
      <%= f.text_area :description %>
      </div>
    </div>
  </li>
  <li class="list-group-item" id="create-todo-list">
    <%= f.submit "Create", id: "bottom-btn" %>
  </li>
<% end %>
</ul>
<div class="nav-link">
<%= link_to 'Back', :back %>
</div>

app/views/todo_lists/show.html.erb
<ul class="list-group">
  <li class="list-group-item" id="todo-lists">
    <div class="page-title-detail"><%= @todo_list.title %></div>
    <div class="todo-list-description-detail"><%= @todo_list.description %></div>
    <%= form_for ([@todo_list, @todo_list.todo_items.build]) do |f| %>
      <div class="row">
        <div>
        <%= f.text_field :content, placeholder: "New Todo", autofocus: "true", id: "todo-item-detail" %>
        </div>
        <%= f.submit 'Add', id: "todo-item-submit-detail" %>
      </div>
    <% end %>
  </li>
  <% if @todo_list.todo_items.count > 0 %>
    <%= render @todo_list.todo_items %>
  <% else %>
  <li class="list-group-item" id="todo-lists">
    No todos have been added.
  </li>
  <% end %>

  <li class="list-group-item" id="todo-bottom-nav">
    <%= link_to 'Back', root_path %>
    |
    <%= link_to 'Edit', edit_todo_list_path(@todo_list) %>
    |
    <%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" } %>
  </li>
</ul>